apiVersion: v1
kind: Service
metadata:
  labels:
    app: hello-time-app
  name: hello-time-app-service
spec:
  ports:
  - name: 80-80
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: hello-time-app
  type: NodePort

